<a href="https://colab.research.google.com/github/Mikhailo88/ChiselniMetody/blob/main/%D0%9B%D0%B0%D0%B1_4_%D0%9E%D0%BB%D1%8C%D1%85%D0%BE%D0%B2%D0%B5%D0%BD%D0%BA%D0%BE_%D0%A4%D0%86%D0%A2_2_8_%D0%92%D0%B0%D1%80_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install numpy

1.Знайти матрицю C = AB-BA:

In [30]:
import numpy as np
A = np.matrix([[1, 1, 1], [0, 1, 1], [0, 0, 1]])
B = np.matrix([[7, 5, 3], [0, 7, 5], [0, 0, 7]])
AB = np.dot(A, B)
BA = np.dot(B, A)
C = AB - BA
print("Матриця C:")
print(C)

Матриця C:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


2.Піднести матрицю до ступеня:

In [7]:
a = np.matrix([[-1, 0, 2], [0, 1, 0], [1, 2, -1]])
c = a ** 2
print("Матриця піднесена до степеня:")
print(c)

Матриця піднесена до степеня:
[[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


3.Знайти добуток матриць:

In [8]:
A = np.matrix([[3, 5], [6, -1]])
B = np.matrix([[2, 1], [-3, 2]])
C = np.dot(A, B)
print("Матриця C:")
print(C)

Матриця C:
[[-9 13]
 [15  4]]


4.Обчислити визначники:

In [9]:
a = np.array([[1, 2, 3], [-1, 2, 1], [1, 3, 2]])
a_det = np.linalg.det(a)
print("Визначник матриці:")
print(a_det.round(2))

Визначник матриці:
-8.0


5.Обчислити визначники:

In [ ]:
a = np.array([[1, 2, 0, 0, 0], [1, 0, 2, 0, 0], [1, 0, 0, 2, 0], [1, 0, 0, 0, 2], [0, 0, 1, 1, 1]])
a_det = np.linalg.det(a)
print("Визначник матриці:")
print(a_det.round(2))

Визначник матриці:
-24.0


6.Знайти обернену матрицю до матриць:

In [10]:
a = np.matrix([[2, 5, 7], [6, 3, 4], [5, -2, -3]])
a_inv = np.linalg.inv(a)
print("Обернена матриця:")
print(a_inv)

Обернена матриця:
[[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]


7.Визначити ранг матриць:


In [11]:
a = np.matrix([[-2, 3, 1, -1], [3, 2, 1, 4], [1, 2, 3, 4], [0, 2, 3, 3]])
rank = np.linalg.matrix_rank(a)
print("Ранг матриці:")
print(rank)

Ранг матриці:
3


Розв'язати систему лінійних рівнянь методом Крамера, матричним методом і м. Гауса. Потім зробити перевірку за допомогою solve() пакету linalg:


Метод Крамера:

In [24]:
def Cramer(coeff, constants):
    det_coeff = np.linalg.det(coeff)
    sol = []
    for i in range(len(coeff)):
        mod_coeff = np.copy(coeff)
        mod_coeff[:, i] = constants
        sol.append(round(np.linalg.det(mod_coeff) / det_coeff, 1))
    return sol
def main():
    a = np.array([[4.0, 1.0, 4.0],
                  [1.0, 1.0, 2.0],
                  [2.0, 1.0, 2.0]])

    b = np.array([-2.0, -1.0, 0.0])

    x_Cramer = Cramer(a, b)
    print("Метод Крамера:", x_Cramer)
if __name__ == "__main__":
    main()


Метод Крамера: [1.0, 2.0, -2.0]


Матричний метод:

In [20]:
def matrix_method(coefficients, constants):
    inverse_matrix = np.linalg.inv(coefficients)
    return np.dot(inverse_matrix, constants)
def main():
    a = np.array([[4.0, 1.0, 4.0],
                  [1.0, 1.0, 2.0],
                  [2.0, 1.0, 2.0]])

    b = np.array([-2.0, -1.0, 0.0])

    x_matrix = matrix_method(a, b)
    print("Матричний метод:", x_matrix)

if __name__ == "__main__":
    main()

Матричний метод: [ 1.  2. -2.]


Метод Гауса:

In [28]:
def Gauss(a, b):
    n = len(b)

    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i, k] / a[k, k]
                a[i, k+1:n] = a[i, k+1:n] - lam * a[k, k+1:n]
                b[i] = b[i] - lam * b[k]

    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]

    return x
def main():
    a = np.array([[4.0, 1.0, 4.0],
                  [1.0, 1.0, 2.0],
                  [2.0, 1.0, 2.0]])

    b = np.array([-2.0, -1.0, 0.0])
    x_Gauss = Gauss(a, b)
    print("Метод Гауса:", x_Gauss)

if __name__ == "__main__":
    main()

Метод Гауса: [ 1.  2. -2.]
Перевірка:
x = [ 0.4  0.  -0.9]


Перевірка методом Solve

In [29]:
a = np.array([[4.0, 1.0, 4.0],
              [1.0, 1.0, 2.0],
              [2.0, 1.0, 2.0]])

b = np.array([-2.0, -1.0, 0.0])

x = np.linalg.solve(a, b)

print('Розв\'язок системи рівнянь:')
print('x =', x.round(1))


Розв'язок системи рівнянь:
x = [ 1.  2. -2.]


# Завдання 2
3. Створіть прямокутну матрицю А, яка має N рядків і M стовпців з випадковими елементами. Визначте середні значення для всіх рядків і стовпців матриці

In [32]:
N = int(input("Введіть кількість рядків (N): "))
M = int(input("Введіть кількість стовпців (M): "))

# Створення матриці з випадковими цілими числами від 1 до 10
A = np.random.randint(1, 11, size=(N, M))

# Виведення матриці
print("Матриця A:")
print(A)

# Обчислення середніх значень для кожного рядка
row_means = np.mean(A, axis=1)
print("\nСередні значення для кожного рядка:")
print(row_means)

# Обчислення середніх значень для кожного стовпця
col_means = np.mean(A, axis=0)
print("\nСередні значення для кожного стовпця:")
print(col_means)



Введіть кількість рядків (N): 3
Введіть кількість стовпців (M): 3
Матриця A:
[[6 1 6]
 [6 1 8]
 [6 6 2]]

Середні значення для кожного рядка:
[4.33333333 5.         4.66666667]

Середні значення для кожного стовпця:
[6.         2.66666667 5.33333333]
